import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 w-full h-12 flex items-center border-b border-zinc-200 px-4 bg-[rgb(0,0,0)] dark:border-zinc-700 z-50">
  <div className="h-full flex items-center gap-2">
    <div>
      <Image
        src="/main_logo.png"
        alt="Main logo"
        width={100}
        height={20}
        priority
      />
    </div>
  </div>
</header>
        
        
        <main className ="flex-1 bg-black">{children}</main>
        <footer className="fixed bottom-0 align-left  px-4 dark:border-zinc-700 bg-black ">
          <div className="h-full flex items-center gap-2">
          <div ><a href="https://github.com/ypa-me/Webscraper">
          <Image
            
            src="/github-logo.png"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
            
          /></a>
           </div>


          </div>
        
      </footer>
        
      </body>
    </html>
  );
}
