import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import localFont from "next/font/local";

const ppmori = localFont({
  src: '../public/fonts/PPMori/PPMori-SemiBold.otf',  
  variable: '--font-ppmori',
  weight: '300',
});

const jetbrains = localFont({
  src: '../public/fonts/JetBrainsMono/JetBrainsMono-Light.ttf',
  variable: '--font-jetbrains',
  weight: '300',
});
const Libre = localFont({
  src: '../public/fonts/LibreBaskerville/LibreBaskerville-Regular.ttf',
  variable: '--font-Libre',
  weight: '300',
});
const Hand=localFont({
  src: '../public/fonts/Hand/ArchitectsDaughter-Regular.ttf',
  variable: '--font-Hand',
  weight: '300',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ppmori.variable} ${jetbrains.variable} ${Libre.variable} ${Hand.variable} `}>
      <body>
        <header className="w-full h-12 flex items-center bg-black/95   z-50">
  <div className="flex items-center px-6">
    <Image
      src="/Black Outline Light.png"
      alt="Main logo"
      width={120}   // Reduced from 150
      height={32}   // Reduced from 100 (fits h-12 perfectly)
      priority
      className="object-contain"
    />
  </div>
</header>
        
        
        <main className ="flex-1 bg-black">{children}</main>
        <footer className=" align-left   dark:border-zinc-700 bg-black ">
          <div className="h-full flex items-center gap-2">
          <div ><a href="https://github.com/ypa-me/Webscraper">
          <Image
            
            src="/github-logo.png"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
            
          /></a>
           </div>


          </div>
        
      </footer>
        
      </body>
    </html>
  );
}
